#cloud-config
autoinstall:
  version: 1
  identity:
     hostname: cop3504-devenv
     username: student
     # pw is "cop3504"
     password: "$6$WZWb89FGmaHFeT05$KR0/bcDC9mMfDm4E0x2ulrfIO9aD5gmVIAXnwH.3FcvnCcwOysL1.EwEPzHmeUfJKD3ibvEMhbjgjnmut5VQk/"
  ssh:
     install-server: yes
     allow-pw: yes
  packages:
    # Building
    - build-essential
    - curl
    - wget
    - git
    - g++
    - cmake
    - python3
    # editors
    - vim
    - emacs
    # progamming utils
    - valgrind
    - gdb
    # project libs
    - libsfml-dev
  late-commands:
    - "wget https://gist.githubusercontent.com/emersonmx/31004a311efb2876d187/raw/eb2b18c543e945c55a592cebe3c0e4dc3d90e299/sfml_hello.cpp -O /home/student/sfml_hello.cpp"
