#cloud-config
autoinstall:
  version: 1
  source:
    id: "ubuntu-desktop-minimal"
  identity:
     hostname: cop3504-devenv
     username: student
     # pw is "cop3504"
     password: "$6$WZWb89FGmaHFeT05$KR0/bcDC9mMfDm4E0x2ulrfIO9aD5gmVIAXnwH.3FcvnCcwOysL1.EwEPzHmeUfJKD3ibvEMhbjgjnmut5VQk/"
  ssh:
     install-server: yes
     allow-pw: yes
  packages:
    # virt
    - virtualbox-guest-x11
    # build tools
    - build-essential
    - curl
    - wget
    - git
    - g++
    - cmake
    - python3
    # editors
    - vim
    - emacs
    # progamming utils
    - valgrind
    - gdb
    # project libs
    - libsfml-dev
  late-commands:
    - wget -O /target/root/postinstall.sh https://raw.githubusercontent.com/0ntu/cop3504-devenv/refs/heads/master/postinstall.sh
    - curtin in-target -- chmod +x /root/postinstall.sh
    - curtin in-target -- bash /root/postinstall.sh
    - rm /target/root/postinstall.sh
